// <auto-generated />
using Demo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420162117_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 26,
                            Name = "Ahmed",
                            Salary = 1234m
                        },
                        new
                        {
                            Id = 2,
                            Age = 36,
                            Name = "Mohamed",
                            Salary = 2234m
                        },
                        new
                        {
                            Id = 3,
                            Age = 46,
                            Name = "Sara",
                            Salary = 4234m
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            Name = "Omar",
                            Salary = 5234m
                        },
                        new
                        {
                            Id = 5,
                            Age = 23,
                            Name = "Ali",
                            Salary = 6234m
                        },
                        new
                        {
                            Id = 6,
                            Age = 36,
                            Name = "Mai",
                            Salary = 7234m
                        },
                        new
                        {
                            Id = 7,
                            Age = 49,
                            Name = "Ramy",
                            Salary = 8234m
                        },
                        new
                        {
                            Id = 8,
                            Age = 18,
                            Name = "Hamada",
                            Salary = 9234m
                        },
                        new
                        {
                            Id = 9,
                            Age = 26,
                            Name = "Hatem",
                            Salary = 10234m
                        },
                        new
                        {
                            Id = 10,
                            Age = 25,
                            Name = "Osama",
                            Salary = 17234m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
